ALTER TABLE users
    ADD COLUMN failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN locked_until TIMESTAMP,
    ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE; 